# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79b9c31c73e4eeb8cd1430b8bc13e8f6aff9ae5ab4364d19a6bd56377446a505cf7d7c57f223257056d8a95d9dc17e132b4f2820ccdec9c3316153fed82caf48

test:
  secret_key_base: b61423422b2e14083316efb1a28ed4863bd279f76b57741f4120320cb0a6f233f27fc5d220a70b3e413326b55ab27b8f789af2926c10f9eb1f3dced1a7db3dd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
